### ISSUE TITLE
Detect compiler crash

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/playground#33]
**Description:**

The following code crashes the compiler, so no output is shown. It would be better to identify such issues and notify the user with an error message.

```ballerina
type AB "A"| record { string f; };

public function main() {
    AB a = { f: "Foo" };
}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kaviththiranga** [comment]
Thanks @Shan1024 for catching this. We will fix this soon.
